danny_rental/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rental/', include('rental.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^rooms/$', views.rooms, name='rooms'),
    url(r'^reservation/$', views.reservation, name='reservation'),
]

rental/models.py
from django.db import models

class Home(models.Model):
    def __unicode__(self):
        return "Home"

class HomePhoto(models.Model):
    room = models.ForeignKey(Home)
    photo = models.ImageField(upload_to='images/about_photo/')
    description = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return self.description

class About(models.Model):
    description = models.TextField()

    def __unicode__(self):
        return str(self.id)

class Room(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    equipment = models.TextField()
    note = models.TextField(blank=True)
    price = models.IntegerField()
    fri_price = models.IntegerField()
    sat_price = models.IntegerField()

    def __unicode__(self):
        return self.name

class RoomPhoto(models.Model):
    room = models.ForeignKey(Room)
    photo = models.ImageField(upload_to='images/room_photo/')

class Transportation(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    
    def __unicode__(self):
        return self.name

class Reservation(models.Model):
    topic = models.CharField(max_length=50)

    def __unicode__(self):
        return self.topic

class TopicContent(models.Model):
    reservation = models.ForeignKey(Reservation)
    subtopic = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.subtopic

class ContactInfo(models.Model):
    phone_number = models.CharField(max_length=50)
    line = models.CharField(max_length=50)
    line_photo = models.ImageField(upload_to='images/contact_photo/', blank=True)
    wechat = models.CharField(max_length=50)
    wechat_photo = models.ImageField(upload_to='images/contact_photo/', blank=True)

    def __unicode__(self):
        return self.phone_number

rental/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Home, HomePhoto, Room, RoomPhoto, About, Transportation, Reservation, ContactInfo

def index(request):
    home = get_object_or_404(Home, pk=1)
    contact_info = get_object_or_404(ContactInfo, pk=1)
    context = {'home': home, 'contact_info': contact_info}
    return render(request, "rental/index.html", context)

def about(request):
    abouts = get_list_or_404(About)
    transportation_list = get_list_or_404(Transportation)
    contact_info = get_object_or_404(ContactInfo, pk=1)
    context = {'abouts': abouts, 'transportation_list': transportation_list, 'contact_info': contact_info}
    return render(request, "rental/about.html", context)

def rooms(request):
    rooms = get_list_or_404(Room)
    contact_info = get_object_or_404(ContactInfo, pk=1)
    context = {'rooms': rooms, 'contact_info': contact_info}
    return render(request, "rental/rooms.html", context)

def reservation(request):
    reservations = get_list_or_404(Reservation)
    contact_info = get_object_or_404(ContactInfo, pk=1)
    context = {'reservations': reservations, 'contact_info': contact_info}
    return render(request, "rental/reservation.html", context)

rental/templates/rental/about.html
{% extends "rental/base.html" %}
{% block content %}
<div class="content-div">
	<div class="title-div">
		<p>關於丹尼</p>
	</div>
	<div class="title-image-div" id="about-title-image-div"></div>
	<div class="about-content-div" id="about-content-div-1">
		<h3>緣起</h3>
		<br/>
{% for about in abouts %}
		<p>{{ about.description }}</p>
{% endfor %}
	</div>
	<div class="about-content-div" id="about-content-div-2">
		<h3>交通</h3>
		</br>
        {% if transportation_list %}
            {% for transportation in transportation_list %}
              
                <h4>{{ transportation.name }}</h4>
                <p>{{ transportation.description }}</p></br>
            {% endfor %}
        {% else %}
          <p>please google it.</p>
        {% endif %}
	</div>
</div>
{% endblock %}

rental/templates/rental/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="This website is built for dannys rental business.">
    <meta name="author" content="Edison Peng">

    <title>DannyHouse逢甲日租</title>
    <link rel="stylesheet" href="{% static "rental/style.css" %}"> 
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	<style>
                #about-title-image-div {
			background: url({% static "rental/table.jpeg" %}) center center;
			background-size: cover;
		}
                #rooms-title-image-div {
                        background: url({% static "rental/pallow.jpg" %}) center center;
                        background-size: cover;
                }
                #reservation-title-image-div {
                        background: url({% static "rental/flower.jpeg" %}) center center;
                        background-size: cover;
                }
		#reservation-main-div {
			background: url({% static "rental/city.jpg" %}) center center;
                        background-size: cover;
		}
	</style>
  </head>
  <body>
      <div class=body-div>
      <nav class="navbar">
        <div class="container-fluid">
            <a class="navbar-brand" href="/rental/"><img src={% static "rental/logo.png" %} /></a>
        </div>
          <div>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/rental/about/">|關於我們</a></li>
              <li><a href="/rental/rooms/">|房型介紹</a></li>
              <li><a href="/rental/reservation/">|訂房須知</a></li>
            </ul>
          </div>
      </nav>

        {% block content %}{% endblock %}
      <br/>
      <div class=gap-div></div>
      <footer>
		<div class=footer-div>
			<div id=qrcode-div>
		                <img src="{{ contact_info.line_photo.url }}"/>
                                <img src="{{ contact_info.wechat_photo.url }}"/>
			</div>
			<div id=info-div>
		                電話：{{ contact_info.phone_number }}</br>
                                Line：{{ contact_info.line }}</br>
		                微信：{{ contact_info.wechat }}</br>
			</div>
		</div>
		<div class=footer-div>
			CopyRight © 2016<br/>
			所有版權未經 逢甲日租DannyHouse 合法授權任意複制 版權必究</br>
		</div>
      </footer>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="{% static "rental/common.js" %}"></script>
  </body>
</html>

rental/templates/rental/index.html
{% extends "rental/base.html" %}
{% block content %}

  <div class="content-div">


        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            {% for photo in home.homephoto_set.all %}
              {% if forloop.first %}
                <div class="item active">
              {% else %}
                <div class="item">
              {% endif %}
                  <img src={{ photo.photo.url }} />
                  <div class="carousel-caption">
                    <h3>{{ photo.description }}</h3>
                  </div>
                </div>
            {% endfor %}
          </div>
        </div>
  </div>
{% endblock %}

rental/templates/rental/reservation.html
{% extends "rental/base.html" %}
{% block content %}
<div class="content-div">
	<div class="title-div">
		<p>訂房需知</p>
	</div>
	<div class="title-image-div" id="reservation-title-image-div"></div>
	<div class="gap-div"></div>
	<div id="reservation-main-div">
		<div id="reservation-content-div">
{% for reservation in reservations %}
<h3>{{ reservation.topic }}</h3>
	{% for subtopic in reservation.topiccontent_set.all %}
                {% if subtopic.subtopic %}
		<h4>{{ subtopic.subtopic }}</h4>
                {% endif %}
                {% if subtopic.description %}
		<p>>> {{ subtopic.description }}</p>
                {% endif %}
	{% endfor %}
	<br/>
{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

rental/templates/rental/room.html
<div id="{{ room.name }}-slide" class="carousel slide">
  <div class="carousel-inner" role="listbox">
    {% for photo in room.roomphoto_set.all %}
      {% if forloop.first %}
        <div class="item active">
          <img src={{ photo.photo.url }} />
        </div>
      {% else %}
        <div class="item">
          <img src={{ photo.photo.url }} />
        </div>
      {% endif %}
    {% endfor %}
  </div>

  <a class="left carousel-control" href="#{{ room.name }}-slide" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#{{ room.name }}-slide" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>
<hr>

<h4>{{ room.name }}</h4>

房型簡介：<br>
{{ room.description }}<br>
<br>

房間設備：<br>
{{ room.equipment }}<br>
<br>

房價表：<br>
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>平日</th>
      <th>週五</th>
      <th>週六</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ room.price }}</td>
      <td>{{ room.fri_price }}</td>
      <td>{{ room.sat_price }}</td>
    </tr>
  </tbody>
</table>

rental/templates/rental/rooms.html
{% extends "rental/base.html" %}
{% block content %}
<div class="content-div">
	<div class="title-div">
		<p>房型介紹</p>
	</div>
	<div class="title-image-div" id="rooms-title-image-div"></div>
	<div></div>
          {% for room in rooms %}
        <div class="room-content-div">
                    <div class="room-photo-div">
                      <img src={{ room.roomphoto_set.first.photo.url }} />
                    </div>
                    <div class="room-des-div">
                      <h3>{{ room.name }}</h3>
                      <p>{{ room.description }}</p>
                    </div>
                    <div class="room-detail-div">
                      <button type="button" class="btn btn-default btn-lg center-block" data-toggle="modal" data-target="#{{ room.name }}">NT {{ room.price  }} 起</button>
                      <div id="{{ room.name }}" class="modal fade" role="dialog">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-body">
 {% include "rental/room.html"%}
                            </div>
	                    <div class="modal-footer">
                             <button type="button" class="btn btn-default" data-dismiss="modal">關閉</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
        </div>
          {% endfor %}
</div>
{% endblock %}